name: C/C++ CI

on:
  - push
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        ls "$PWD"
        ls "$PWD"/build

    - run: ls /proc/sys/fs/binfmt_misc || true
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y binfmt-support
    - run: ls /proc/sys/fs/binfmt_misc || true
    - run: sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
    - run: ls /proc/sys/fs/binfmt_misc || true
    - run: cat /proc/sys/fs/binfmt_misc/status

    - run: docker build -t cosmopolitan .
    - run: docker run --rm -v$PWD:/workdir cosmopolitan ls workdir/build
    # https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html
    - run: docker run --rm --user root -v$PWD:/workdir cosmopolitan sh -c "mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register; make -C workdir -j1 -O all"
    - run: o//examples/hello.com
    - run: set -o pipefail; find o -name \*.com | xargs ls -rShal | less
